(setq custom-theme-directory (concat user-emacs-directory "dmaz/"))
(let ((dmaz--initing t))
  (require 'dmaz-variables)
  ;; You can keep system- or user-specific customizations here (use `dmaz-visit-system-config`)
  (setq dmaz-system-config (concat user-emacs-directory "dmaz/dmaz-sys-specific/" system-name ".el")
        dmaz-user-config (concat user-emacs-directory "dmaz/dmaz-sys-specific/dmaz-login-specific/" user-login-name ".el")
        dmaz-user-dir (concat user-emacs-directory "dmaz/dmaz-sys-specific/dmaz-login-specific/" user-login-name)
        custom-file dmaz-system-config)
  (when (file-exists-p dmaz-system-config) (load dmaz-system-config))
  (when (file-exists-p dmaz-user-config) (load dmaz-user-config))
  (load-theme 'dmaz-general t))
(dmaz-custom-set-all-variables)

(provide 'dmaz-customize)
